apiVersion: v1
kind: Service
metadata:
  namespace: pyttpass
  name: pyttpass-service
  labels:
    app: pyttpass
spec:
  type: NodePort
  selector:
    app: pyttpass
  ports:
    - name: http-pyttpass
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
